# Generated by Django 4.0 on 2022-01-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avilable',
            new_name='is_available',
        ),
    ]
